version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    links:
      - "app:app"
    command: [nginx, '-g', 'daemon off;']
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    command: ./entrypoint.sh
