version: "3"
services:
  rails:
    build: .
    command: ./entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/var/lib/sandbox-todo-app
      - bundle_install:/var/lib/sandbox-todo-app/vendor/bundle
      - bundle:/var/lib/sandbox-todo-app/.bundle
      - node_modules:/var/lib/sandbox-todo-app/node_modules
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis
    tty: true
    stdin_open: true
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
