version: "2"
services:
  # 毎回 bundle installしなくてもいいように
  # ストレージデータを保存していく
  datastore:
    image: busybox
    volumes:
      - mysql-data:/var/lib/mysql
      - redis-data:/data
      - bundle_install:/var/lib/sandbox-todo-app/vendor/bundle
      - bundle:/var/lib/sandbox-todo-app/.bundle
      - node_modules:/var/lib/sandbox-todo-app/node_modules
  rails:
    build: .
    command: ./entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/var/lib/sandbox-todo-app
    volumes_from:
      - datastore
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis
    tty: true
    stdin_open: true
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes_from:
      - datastore
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes_from:
      - datastore

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
