# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7975007e69754d497531e612511b6be53bc2b5f8b004f464280a9d273dbf3edb2006034ce11e23a11e3db319547722106e8392204274da56eb80752fac1aff6

test:
  secret_key_base: 13a390ac8fd69a28727334559fd6726b412b1ec629c301192fbb98d1e6da78cba1e39645c8ffef1db1992d549797dcde0acc33ce8587be7a961a8120e6e58c83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
